### ISSUE TITLE
Examples of use or screencast of how this package should work?

### ISSUE THREAD

**Issue by mgraham** [natask/org-roam-search#6]
I'm having trouble getting this package to work properly, and part of the problem is I don't know what to run or what results to expect.

When I type `M-x org-roam-search-node-find` I get a list of nodes to pick from (same as `M-x org-roam-node-find`).  What command do I run to be able to enter a search expression to search for nodes?

**Comment by natask** [comment]
I have updated the readme and also look at https://github.com/natask/sexp-string#custom-pexs  for syntax.

**Comment by mgraham** [comment]
Thank you @natask!
